In [18]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [19]:
df=pd.read_csv(r"C:\Users\Swamy\OneDrive\Desktop\22\Depression Student Dataset.csv")

In [20]:
df

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,28,2.0,4.0,7-8 hours,Moderate,Yes,9,2,Yes,No
1,Male,28,4.0,5.0,5-6 hours,Healthy,Yes,7,1,Yes,No
2,Male,25,1.0,3.0,5-6 hours,Unhealthy,Yes,10,4,No,Yes
3,Male,23,1.0,4.0,More than 8 hours,Unhealthy,Yes,7,2,Yes,No
4,Female,31,1.0,5.0,More than 8 hours,Healthy,Yes,4,2,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
497,Male,26,5.0,2.0,More than 8 hours,Unhealthy,No,8,3,No,Yes
498,Male,24,2.0,1.0,Less than 5 hours,Unhealthy,Yes,8,5,No,Yes
499,Female,23,3.0,5.0,5-6 hours,Healthy,No,1,5,Yes,No
500,Male,33,4.0,4.0,More than 8 hours,Healthy,No,8,1,Yes,No
501,Male,18,5.0,3.0,More than 8 hours,Unhealthy,No,6,2,Yes,Yes

In [21]:
encode = LabelEncoder()
df_categorical =[]
for column in df.columns:
    if df[column].dtypes=="object":
        df_categorical.append(column)
for column in df_categorical: 
    df[column] = encode.fit_transform(df[column])

In [22]:
from sklearn.model_selection import train_test_split

x = df.drop(columns=["Depression"])
y =df["Depression"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [29]:
x_train

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness
116,1,22,4.0,2.0,3,2,0,10,1,1
45,1,20,3.0,5.0,3,2,0,11,4,0
16,1,23,5.0,2.0,3,1,0,10,4,0
464,1,32,3.0,1.0,1,2,1,1,4,0
358,1,29,2.0,4.0,3,2,0,10,5,0
...,...,...,...,...,...,...,...,...,...,...
106,0,25,2.0,2.0,3,1,0,11,2,1
270,1,28,5.0,4.0,3,1,1,6,4,0
348,1,19,3.0,1.0,2,2,0,10,4,0
435,0,32,3.0,1.0,1,1,1,7,3,1
102,0,20,2.0,5.0,3,2,1,4,2,0

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [43]:
lr=LogisticRegression()

In [24]:
model_list = [
    LogisticRegression(),
    DecisionTreeClassifier(ccp_alpha=0.001),
    RandomForestClassifier(),
]

from sklearn.metrics import accuracy_score
results={}
for model in model_list:
    model.fit(x_train, y_train)
    
    y_pred = model.predict(x_test)
    
    accuracy = accuracy_score(y_test, y_pred)

    results[type(model).__name__] = accuracy

for model_name, accuracy in results.items():
    print(model_name , (accuracy*100))

LogisticRegression 96.02649006622516
DecisionTreeClassifier 85.43046357615894
RandomForestClassifier 94.03973509933775

In [25]:
max_classifier = max(results, key=results.get)
max_accuracy = results[max_classifier]

print("The classifier with the maximum accuracy is:", max_classifier ,"with accuracy" ,max_accuracy)

The classifier with the maximum accuracy is: LogisticRegression with accuracy 0.9602649006622517

In [30]:
x_test

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness
268,0,33,4.0,3.0,1,0,0,2,2,0
73,1,26,3.0,4.0,3,2,1,11,5,0
289,0,28,3.0,2.0,2,0,1,10,3,1
155,0,29,3.0,2.0,2,1,0,5,2,1
104,1,19,2.0,5.0,0,0,0,9,1,1
...,...,...,...,...,...,...,...,...,...,...
23,0,33,3.0,2.0,1,1,0,11,5,1
311,1,27,1.0,2.0,1,0,1,10,1,0
262,0,19,1.0,1.0,3,2,0,6,2,1
430,1,28,3.0,2.0,3,0,0,3,1,1
5,1,19,4.0,4.0,0,2,1,1,4,1

In [31]:
from sklearn.metrics import confusion_matrix, classification_report

# Predict on the test set
y_pred = model.predict(x_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[66  5]
 [ 4 76]]

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.93      0.94        71
           1       0.94      0.95      0.94        80

    accuracy                           0.94       151
   macro avg       0.94      0.94      0.94       151
weighted avg       0.94      0.94      0.94       151

In [32]:
from sklearn.model_selection import cross_val_score

# Perform 5-fold cross-validation
cv_scores = cross_val_score(model, x, y, cv=5)

# Print the average cross-validation score
print(f"Average Cross-Validation Score: {cv_scores.mean():.4f}")

Average Cross-Validation Score: 0.8985

In [34]:
from sklearn.model_selection import GridSearchCV

# Define parameter grid
param_grid = {'C': [0.01, 0.1, 1, 10, 100], 'solver': ['liblinear', 'saga']}

# GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5, n_jobs=-1)
grid_search.fit(x, y)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best Cross-validation Score:", grid_search.best_score_)

Best Parameters: {'C': 1, 'solver': 'liblinear'}
Best Cross-validation Score: 0.9561980198019802

In [36]:
# Final model training with the best parameters
final_model = LogisticRegression(C=1, solver='liblinear')
final_model.fit(x_train, y_train)

# Evaluate on the test set (if you have it)
y_pred_test = final_model.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_test))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_test))

Confusion Matrix:
[[68  3]
 [ 3 77]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.96      0.96        71
           1       0.96      0.96      0.96        80

    accuracy                           0.96       151
   macro avg       0.96      0.96      0.96       151
weighted avg       0.96      0.96      0.96       151

In [48]:
df

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,28,2.0,4.0,1,1,1,9,2,1,0
1,1,28,4.0,5.0,0,0,1,7,1,1,0
2,1,25,1.0,3.0,0,2,1,10,4,0,1
3,1,23,1.0,4.0,3,2,1,7,2,1,0
4,0,31,1.0,5.0,3,0,1,4,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...
497,1,26,5.0,2.0,3,2,0,8,3,0,1
498,1,24,2.0,1.0,2,2,1,8,5,0,1
499,0,23,3.0,5.0,0,0,0,1,5,1,0
500,1,33,4.0,4.0,3,0,0,8,1,1,0
501,1,18,5.0,3.0,3,2,0,6,2,1,1

In [50]:
# Check columns used during training (train data)
print(x_train.columns)

Index(['Gender', 'Age', 'Academic Pressure', 'Study Satisfaction',
       'Sleep Duration', 'Dietary Habits',
       'Have you ever had suicidal thoughts ?', 'Study Hours',
       'Financial Stress', 'Family History of Mental Illness'],
      dtype='object')

In [51]:
print(model.feature_names_in_)

['Gender' 'Age' 'Academic Pressure' 'Study Satisfaction' 'Sleep Duration'
 'Dietary Habits' 'Have you ever had suicidal thoughts ?' 'Study Hours'
 'Financial Stress' 'Family History of Mental Illness']

22

In [64]:
import pandas as pd

# Load your dataset (ensure the data is in a DataFrame)
data = df

# Verify the structure of the data to ensure it is a DataFrame
print(type(data))  # Should print: <class 'pandas.core.frame.DataFrame'>

# Preview the first few rows of the dataset
print(data.head())

# If you are working with a dictionary, you can convert it to a DataFrame:
# Example: data = pd.DataFrame(your_dict)

# Handle missing values (if any), for simplicity, let's drop rows with missing values
data = data.dropna()

# Encode categorical features (if any)
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])

# Define feature columns (X) and target column (y)
X = data.drop('Depression', axis=1)  # Drop the target column 'Depression'
y = data['Depression']  # This is the target variable

# Split the dataset into training and testing sets (80% training, 20% testing)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the Logistic Regression model
from sklearn.linear_model import LogisticRegression


lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

# Make predictions on the test set
y_pred = lr.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))

<class 'pandas.core.frame.DataFrame'>
   Gender  Age  Academic Pressure  Study Satisfaction  Sleep Duration  \
0       1   28                2.0                 4.0               1
1       1   28                4.0                 5.0               0
2       1   25                1.0                 3.0               0
3       1   23                1.0                 4.0               3
4       0   31                1.0                 5.0               3

   Dietary Habits  Have you ever had suicidal thoughts ?  Study Hours  \
0               1                                      1            9
1               0                                      1            7
2               2                                      1           10
3               2                                      1            7
4               0                                      1            4

   Financial Stress  Family History of Mental Illness  Depression
0                 2                                 1           0
1                 1                                 1           0
2                 4                                 0           1
3                 2                                 1           0
4                 2                                 1           0
Accuracy: 0.9702970297029703
Confusion Matrix:
[[46  2]
 [ 1 52]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.96      0.97        48
           1       0.96      0.98      0.97        53

    accuracy                           0.97       101
   macro avg       0.97      0.97      0.97       101
weighted avg       0.97      0.97      0.97       101

In [61]:
df

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,28,2.0,4.0,1,1,1,9,2,1,0
1,1,28,4.0,5.0,0,0,1,7,1,1,0
2,1,25,1.0,3.0,0,2,1,10,4,0,1
3,1,23,1.0,4.0,3,2,1,7,2,1,0
4,0,31,1.0,5.0,3,0,1,4,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...
497,1,26,5.0,2.0,3,2,0,8,3,0,1
498,1,24,2.0,1.0,2,2,1,8,5,0,1
499,0,23,3.0,5.0,0,0,0,1,5,1,0
500,1,33,4.0,4.0,3,0,0,8,1,1,0
501,1,18,5.0,3.0,3,2,0,6,2,1,1

In [ ]:
# Sample input data (new observation to predict)
input_data = {
    'Gender': [0],  # 0 for Male (assuming Gender is already encoded)
    'Age': [22],
    'Academic Pressure': [3],
    'Study Satisfaction': [2],
    'Sleep Duration': [7.5],  # hours
    'Dietary Habits': [2],
    'Have you ever had suicidal thoughts ?': [0],  # 0 for no
    'Study Hours': [5],
    'Financial Stress': [2],
    'Family History of Mental Illness': [1]  # 1 for yes
}

# Convert the input data to a pandas DataFrame
input_df = pd.DataFrame(input_data)

# Ensure the columns are in the same order as the training data
input_df = input_df[['Gender', 'Age', 'Academic Pressure', 'Study Satisfaction', 
                     'Sleep Duration', 'Dietary Habits', 'Have you ever had suicidal thoughts ?',
                     'Study Hours', 'Financial Stress', 'Family History of Mental Illness']]

# Use the trained model to predict
prediction = model.predict(input_df)

# Output the result
if prediction == 1:
    print("The prediction indicates a higher likelihood of depression.")
else:
    print("The prediction indicates a lower likelihood of depression.")

The prediction indicates a lower likelihood of depression.

In [67]:
# Save the model
import pickle
with open('logistic_regression_model.pkl', 'wb') as file:
    pickle.dump(final_model, file)

# Load the model (when deploying)
with open('logistic_regression_model.pkl', 'rb') as file:
    model = pickle.load(file)